repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: pretty-format-json
        args: ['--autofix']
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: local
    hooks:
    -   id: prospector
        name: prospector
        entry: prospector
        language: system
        types: [python]
        require_serial: true