# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

# for html
title: {{cookiecutter.project_name}}
logo: notebooks/figures/logo_png.png

# for pdf/latex
project: {{cookiecutter.project_name}}
author: {{cookiecutter.author_name}}
sphinx:
  config:
    latex_logo: 'notebooks/figures/logo_jpg2300.jpg'


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  #path_to_book: notebooks  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
