site_name: Cookiecutter Data Science
site_description: A project template and directory structure for Python data science projects.
site_favicon: favicon.ico
repo_url: https://github.com/Giving-Tuesday/cookiecutter-data-science
edit_uri: edit/master/docs/docs
copyright: 
google_analytics: ['UA-54096005-4', 'auto']
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: index.md
