site_name: Gatlen's Opinionated Template (GOTem)
site_description: A modern, opinionated full-stack CookieCutter project template that prioritizes developer experience and cutting-edge tools. Built on (and synced with) the foundation of CookieCutter Data Science (CCDS) V2, this template incorporates carefully selected defaults, dependency stack, customizations, and contemporary best practices for Python development, research projects, and academic work.
site_url: https://gatlenculp.github.io/gatlens-opinionated-template/
repo_url: https://github.com/GatlenCulp/gatlens-opinionated-template
edit_uri: edit/master/docs/docs
copyright: Upstream maintained by the friendly folks at <a target=_blanks href="https://www.drivendata.org">DrivenData</a>, fork maintained by <a target=_blanks href="https://gatlen.notion.site">Gatlen Culp</a>.
theme:
  favicon: favicon.ico
  features:
    - navigation.instant
    - toc.integrate
  logo: gotem.png
  name: material
  custom_dir: overrides
  palette:
    primary: custom
    accent: custom
  font:
    text: Work Sans
    code: Space Mono
nav:
  - ğŸ  Home: index.md
  - ğŸ› ï¸ Core Tools: core-tools.md
  - â“ Why ccds?: why.md
  - ğŸ—¯ï¸ Opinions: opinions.md
  - ğŸ“‘ Using the template: using-the-template.md
  - âš™ï¸ All options: all-options.md
  - â¤ï¸ Contributing: contributing.md
  - ğŸ”— Related projects: related.md
extra:
  analytics:
    provider: google
    property: G-DX14MC19WY
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - toc:
      toc_depth: 2
plugins:
  - include-markdown
  - termynal:
      title: bash
      buttons: macos
      prompt_literal_start:
        - "$"
  - gen-files:
      scripts:
        - scripts/generate-termynal.py
        - scripts/configuration-table.py
